Fix to allow float type parameter sent as string
Proposed change adds two acceptance conditions to the check_float function to allow valid int or float types to be sent as strings, which Etsy expects in the updateListing PUT RESTful JSON request.  Without fix, code such as:

rt = self.etsy_api.updateListing(listing_id=new_product_id,
   item_weight='\'{0}\''.format(l_weight),
   item_length='\'{0}\''.format(l_lngth), item_width='\'{0}\''.format(l_width),    item_height='\'{0}\''.format(l_width),
   item_dimensions_unit='in', item_weight_unit='oz')

causes error like:

>>> etsy_api.updateListing(listing_id=6XXXXX7, item_weight='5.0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/etsy/_core.py", line 102, in __call__
    return self.invoke(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/etsy/_core.py", line 136, in invoke
    self.type_checker(self.spec, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/etsy/_core.py", line 41, in __call__
    "Bad value for parameter %s of type '%s' - %s" % (k, t, v))
ValueError: Bad value for parameter item_weight of type 'float' - 5.0

or a garbled 'Could not decode response from Etsy as JSON' OAuth error.

This is fabulous code otherwise, thank you!